version: '3.4'

services:
  circlesapi:
    image: circlesapi:latest
    build:
      context: .
      dockerfile: Services/Circles.Api/Dockerfile

  squaresapi:
    image: squaresapi:latest
    build:
      context: .
      dockerfile: Services/Squares.Api/Dockerfile


  shapesapigateway:
    image: shapesapigateway:latest
    build:
      context: .
      dockerfile: ApiGateway/Shapes.ApiGateway/Dockerfile


  shapesweb:
    image: shapesweb:latest
    build:
      context: .
      dockerfile: Web/ShapesWeb/Dockerfile