---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: shapesweb
  labels:
    app: shapesweb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: shapesweb
    spec:
      containers:
      - name: shapesweb
        image: nishanil/shapesweb:latest
        env:
        - name: CirclesUrl
          value: "<yourapigatewayip>"
        - name: SquaresUrl
          value: "<yourapigatewayip>"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: shapesweb
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: shapesweb