---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shapesweb-deployment
  labels:
    app: shapesweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shapesweb
  template:
    metadata:
      labels:
        app: shapesweb
    spec:
      containers:
      - name: shapesweb
        image: nishanil/shapesweb:latest
        env:
        - name: CirclesUrl
          value: "http://192.168.246.77:30850"
        - name: SquaresUrl
          value: "http://192.168.246.77:30850"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: shapesweb
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: shapesweb